# Generated by Django 6.0.4 on 2026-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_portfolio_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
